name: algostudio_flutter_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  image_picker: 0.8.6
  cached_network_image: 3.2.3
  flutter_cache_manager: 3.3.0
  google_fonts: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

